# Generated by Django 5.0.2 on 2024-02-22 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EEUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='ФИО')),
                ('user_type', models.CharField(choices=[('supervisor', 'Руководитель'), ('worker', 'Рабочий')], max_length=255, verbose_name='Тип пользователя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('tg_id', models.BigIntegerField(default=0, verbose_name='Телеграм айди')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('file_id', models.BigIntegerField(default=0, verbose_name='Файл айди')),
                ('result', models.CharField(max_length=255, verbose_name='Результат')),
                ('result_file_id', models.BigIntegerField(default=0, verbose_name='Файл результата айди')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('finish_date', models.DateField(null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('progress', 'В процессе'), ('completed', 'Выполнено')], default='created', max_length=255, verbose_name='Статус')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='bot.eeuser', verbose_name='Создатель')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.eeuser', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Поручение',
                'verbose_name_plural': 'Поручения',
            },
        ),
    ]
