# Generated by Django 5.0.2 on 2024-02-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_task_executor_alter_task_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Файл айди'),
        ),
    ]
