# Generated by Django 5.0.2 on 2024-02-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_task_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_type',
            field=models.CharField(choices=[('photo', 'Фото'), ('document', 'Документ')], max_length=255, null=True, verbose_name='Тип файла'),
        ),
    ]
