# Generated by Django 5.0.2 on 2024-02-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_task_file_type_alter_task_result_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='message_id',
            field=models.BigIntegerField(default=0, verbose_name='Айди сообщения'),
        ),
    ]
